<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251127000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create contact table with search indexes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE contact (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id UUID NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(32) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT contact_pkey PRIMARY KEY (id),
    CONSTRAINT contact_external_id_unique UNIQUE (external_id),
    CONSTRAINT contact_email_unique UNIQUE (email)
)
SQL
        );

        $this->addSql('CREATE INDEX contact_firstname_idx ON contact (firstname)');
        $this->addSql('CREATE INDEX contact_lastname_idx ON contact (lastname)');
        $this->addSql('CREATE INDEX contact_email_idx ON contact (email)');
        $this->addSql('CREATE INDEX contact_phone_idx ON contact (phone)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE contact');
    }
}


