<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251128010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add manager table, link contacts to managers via nullable manager_id, and seed two managers.';
    }

    public function up(Schema $schema): void
    {
        // Create manager table
        $this->addSql(
            'CREATE TABLE manager (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id UUID NOT NULL,
                firstname VARCHAR(100) NOT NULL,
                lastname VARCHAR(100) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
            )'
        );

        $this->addSql('CREATE UNIQUE INDEX UNIQ_MANAGER_EXTERNAL_ID ON manager (external_id)');
        $this->addSql('CREATE INDEX IDX_MANAGER_LASTNAME ON manager (lastname)');

        // Seed a couple of managers for demo/testing purposes.
        // In a real project this would live in dedicated fixtures, not in a migration.
        $now = (new \DateTimeImmutable())->format('Y-m-d H:i:s');

        $this->addSql(
            "INSERT INTO manager (external_id, firstname, lastname, created_at, updated_at) VALUES
             ('11111111-1111-1111-1111-111111111111', 'Alice', 'Manager', :now, :now),
             ('22222222-2222-2222-2222-222222222222', 'Bob', 'Supervisor', :now, :now)",
            ['now' => $now]
        );

        // Add nullable foreign key on contact to managers.
        $this->addSql('ALTER TABLE contact ADD COLUMN manager_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_CONTACT_MANAGER_ID ON contact (manager_id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_CONTACT_MANAGER FOREIGN KEY (manager_id) REFERENCES manager (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // Drop foreign key and column on contact
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_CONTACT_MANAGER');
        $this->addSql('DROP INDEX IDX_CONTACT_MANAGER_ID');
        $this->addSql('ALTER TABLE contact DROP COLUMN manager_id');

        // Drop manager table and its indexes
        $this->addSql('DROP INDEX UNIQ_MANAGER_EXTERNAL_ID');
        $this->addSql('DROP INDEX IDX_MANAGER_LASTNAME');
        $this->addSql('DROP TABLE manager');
    }
}


